name: Playwright Tests
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:        # manual trigger from GH UI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed for gh-pages deployment
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # currently v24 is on my machine
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
   
    - name: Run Playwright tests      
      run: | # if condition (manual trigger only) to update playwright snapshots
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then 
          npm run lint && npm run playwright -- --update-snapshots
        else
          npm run testscript  # picks script from package.json. By default runs all projects defined in config
        fi        
      env: 
        base_url: ${{ secrets.BASE_URL }}
        api_timeout: ${{ secrets.API_TIMEOUT }}
        test_global_timeout: ${{ secrets.TEST_GLOBAL_TIMEOUT }}
        test_expect_timeout: ${{ secrets.TEST_EXPECT_TIMEOUT }}
        admin_user_name: ${{ secrets.ADMIN_USER_NAME }}
        admin_password: ${{ secrets.ADMIN_PASSWORD }}
        ess_user_name: ${{ secrets.ESS_USER_NAME }}
        ess_user_password: ${{ secrets.ESS_USER_PASSWORD }}
        test_employee_dir: "storage"
        mailtrap_base_url: ${{ secrets.MAILTRAP_BASE_URL }}
        mailtrap_api_token: ${{ secrets.MAILTRAP_API_TOKEN }}
        mailtrap_smtp_user_name: ${{ secrets.MAILTRAP_SMTP_USER_NAME }}
        mailtrap_smtp_user_Password: ${{ secrets.MAILTRAP_SMTP_USER_PASSWORD }}
        mailtrap_account_id: ${{ secrets.MAILTRAP_ACCOUNT_ID }}
        mailtrap_inbox_id: ${{ secrets.MAILTRAP_INBOX_ID }}

    - name: Commit updated snapshots
      if: github.event_name == 'workflow_dispatch' 
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add tests/
        git commit -m "chore: update Linux baseline screenshots" || echo "No changes"
        git push

    - name: Upload Playwright HTML report
      if: always()                # upload even on test failure
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 14
    
    - name: Upload Playwright traces
      if: always() && github.event_name != 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: test-results/          # traces land here by default
        retention-days: 7

    - name: Download previous Allure history
      uses: actions/download-artifact@v4
      if: always()
      continue-on-error: true        # won't fail if first run
      with:
        name: allure-history
        path: allure-results/history
    
    - name: Generate Allure Report
      if: always()
      run: npx --yes --package=allure-commandline allure generate allure-results --clean --output allure-report
      # --package=allure-commandline tells npx which package to pull, allure is the actual binary to run. --yes skips the install confirmation prompt on CI.    

    - name: Upload Allure history for next run
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-history
        path: allure-report/history/
        retention-days: 30   
        overwrite: true   

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
       name: allure-report
       path: allure-report/
       retention-days: 14

    - name: Deploy Allure Report to GitHub Pages
      if: always() && github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v4
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub injects it automatically
       publish_dir: ./allure-report
